[package]
name = "cofy-server-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
http = "1.1.0"
serde_json = "1.0.117"
tokio = { version = "1.37.0", features = ["rt", "net", "macros", "rt-multi-thread", "io-util"]  }
toml = "0.8"
