[package]
name = "cofy-server-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0"
http = "1.1"
serde_json = "1.0"
log = "0.4"
tokio = { version = "1.37", features = [
    "macros",
    "net",
    "rt-multi-thread",
] }
toml = "0.8"
