name: CI

on:
  push:
    paths: ['**.rs', '**.toml', '**/ci.yml', '**.lock']
  pull_request:
    paths: ['**.rs', '**.toml', '**/ci.yml', '**.lock']
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: '-C target-cpu=native'

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v4
      - name: update to ${{ matrix.toolchain }} rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      - name: build
        run: cargo b -v
